modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Replanting%20Crops"
logoFile="icon.png"

[[mods]]
modId="replantingcrops"
version="5.1"
displayName="Replanting Crops"
displayURL="https://curseforge.com/minecraft/mc-mods/replanting-crops"
authors="Rick South"
description='''Automatically replants/replaces/reseeds crops harvested with seeds from drops, negated by holding the sneak button.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.replantingcrops]]
    modId="collective"
    mandatory=true
    versionRange="[6.43,)"
    ordering="NONE"
    side="BOTH"